### ISSUE TITLE
Question: is lefilament/odoo:14.0 ready for production ?

### ISSUE THREAD

**Issue by nqb** [lefilament/odoo_docker#1]
Hello,

As you probably know, I'm trying to put a Odoo instance in production using Le Filament's Ansible role and got some issues.

I would like to know if `lefilament/odoo:14.0` image can be used in production at the moment with all Odoo modules developed by Le Filament.

Thanks for your feedback.

**Comment by remi-filament** [comment]
Dear @nqb normally you could use it in production. However we do not (yet), we only use it in demo/test environment and therefore we have not created any additional module for that version. (we are still using 12.0 and most of the additional modules we developed for v10.0 and v12.0 can be found on our GitLab instance here : [https://sources.le-filament.com/lefilament](https://sources.le-filament.com/lefilament)
Also you will find that many OCA modules are not yet migration to version 14.0.

**Comment by nqb** [comment]
Thanks for your feedback. This was my feeling too.
